apiVersion: v1
kind: Service
metadata:
  name: node-b-svc
spec:
  selector:
    app: warehouse-node-b
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-node-b
  template:
    metadata:
      labels:
        app: warehouse-node-b
    spec:
      containers:
      - name: node
        image: warehouse-node:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        args: ["-id", "node-B", "-port", "50051", "-peers", "node-a-svc:50051,node-c-svc:50051"]