// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/warehouse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clocks        map[string]int32       `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetClocks() map[string]int32 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

// Client <-> Node Messages
type UpdateStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemId         string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStockRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewQuantity   int32                  `protobuf:"varint,2,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	CurrentClock  *VectorClock           `protobuf:"bytes,3,opt,name=current_clock,json=currentClock,proto3" json:"current_clock,omitempty"` // Returns the updated clock after the operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *UpdateStockResponse) GetCurrentClock() *VectorClock {
	if x != nil {
		return x.CurrentClock
	}
	return nil
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CurrentClock  *VectorClock           `protobuf:"bytes,2,opt,name=current_clock,json=currentClock,proto3" json:"current_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetStockResponse) GetCurrentClock() *VectorClock {
	if x != nil {
		return x.CurrentClock
	}
	return nil
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{5}
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]int32       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CurrentClock  *VectorClock           `protobuf:"bytes,2,opt,name=current_clock,json=currentClock,proto3" json:"current_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *GetInventoryResponse) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetInventoryResponse) GetCurrentClock() *VectorClock {
	if x != nil {
		return x.CurrentClock
	}
	return nil
}

// Node <-> Node Messages
type SyncLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	Clock         *VectorClock           `protobuf:"bytes,2,opt,name=clock,proto3" json:"clock,omitempty"`                                                                                    // The vector clock of the sending node
	Inventory     map[string]int32       `protobuf:"bytes,3,rep,name=inventory,proto3" json:"inventory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // The current state of the sender's inventory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLedgerRequest) Reset() {
	*x = SyncLedgerRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLedgerRequest) ProtoMessage() {}

func (x *SyncLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLedgerRequest.ProtoReflect.Descriptor instead.
func (*SyncLedgerRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *SyncLedgerRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *SyncLedgerRequest) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *SyncLedgerRequest) GetInventory() map[string]int32 {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type SyncLedgerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MergedClock     *VectorClock           `protobuf:"bytes,2,opt,name=merged_clock,json=mergedClock,proto3" json:"merged_clock,omitempty"`                                                                                        // The new clock after resolving conflicts
	MergedInventory map[string]int32       `protobuf:"bytes,3,rep,name=merged_inventory,json=mergedInventory,proto3" json:"merged_inventory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // The definitive inventory state after merge
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncLedgerResponse) Reset() {
	*x = SyncLedgerResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLedgerResponse) ProtoMessage() {}

func (x *SyncLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLedgerResponse.ProtoReflect.Descriptor instead.
func (*SyncLedgerResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *SyncLedgerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncLedgerResponse) GetMergedClock() *VectorClock {
	if x != nil {
		return x.MergedClock
	}
	return nil
}

func (x *SyncLedgerResponse) GetMergedInventory() map[string]int32 {
	if x != nil {
		return x.MergedInventory
	}
	return nil
}

var File_proto_warehouse_proto protoreflect.FileDescriptor

const file_proto_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x15proto/warehouse.proto\"z\n" +
	"\vVectorClock\x120\n" +
	"\x06clocks\x18\x01 \x03(\v2\x18.VectorClock.ClocksEntryR\x06clocks\x1a9\n" +
	"\vClocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"V\n" +
	"\x12UpdateStockRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\"\x85\x01\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnew_quantity\x18\x02 \x01(\x05R\vnewQuantity\x121\n" +
	"\rcurrent_clock\x18\x03 \x01(\v2\f.VectorClockR\fcurrentClock\"*\n" +
	"\x0fGetStockRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"a\n" +
	"\x10GetStockResponse\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x121\n" +
	"\rcurrent_clock\x18\x02 \x01(\v2\f.VectorClockR\fcurrentClock\"\x15\n" +
	"\x13GetInventoryRequest\"\xbb\x01\n" +
	"\x14GetInventoryResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .GetInventoryResponse.ItemsEntryR\x05items\x121\n" +
	"\rcurrent_clock\x18\x02 \x01(\v2\f.VectorClockR\fcurrentClock\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xdc\x01\n" +
	"\x11SyncLedgerRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\"\n" +
	"\x05clock\x18\x02 \x01(\v2\f.VectorClockR\x05clock\x12?\n" +
	"\tinventory\x18\x03 \x03(\v2!.SyncLedgerRequest.InventoryEntryR\tinventory\x1a<\n" +
	"\x0eInventoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf8\x01\n" +
	"\x12SyncLedgerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\fmerged_clock\x18\x02 \x01(\v2\f.VectorClockR\vmergedClock\x12S\n" +
	"\x10merged_inventory\x18\x03 \x03(\v2(.SyncLedgerResponse.MergedInventoryEntryR\x0fmergedInventory\x1aB\n" +
	"\x14MergedInventoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xff\x01\n" +
	"\x10InventoryManager\x12=\n" +
	"\x10UpdateLocalStock\x12\x13.UpdateStockRequest\x1a\x14.UpdateStockResponse\x125\n" +
	"\n" +
	"SyncLedger\x12\x12.SyncLedgerRequest\x1a\x13.SyncLedgerResponse\x124\n" +
	"\rGetLocalStock\x12\x10.GetStockRequest\x1a\x11.GetStockResponse\x12?\n" +
	"\x10GetFullInventory\x12\x14.GetInventoryRequest\x1a\x15.GetInventoryResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_warehouse_proto_rawDescOnce sync.Once
	file_proto_warehouse_proto_rawDescData []byte
)

func file_proto_warehouse_proto_rawDescGZIP() []byte {
	file_proto_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)))
	})
	return file_proto_warehouse_proto_rawDescData
}

var file_proto_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_warehouse_proto_goTypes = []any{
	(*VectorClock)(nil),          // 0: VectorClock
	(*UpdateStockRequest)(nil),   // 1: UpdateStockRequest
	(*UpdateStockResponse)(nil),  // 2: UpdateStockResponse
	(*GetStockRequest)(nil),      // 3: GetStockRequest
	(*GetStockResponse)(nil),     // 4: GetStockResponse
	(*GetInventoryRequest)(nil),  // 5: GetInventoryRequest
	(*GetInventoryResponse)(nil), // 6: GetInventoryResponse
	(*SyncLedgerRequest)(nil),    // 7: SyncLedgerRequest
	(*SyncLedgerResponse)(nil),   // 8: SyncLedgerResponse
	nil,                          // 9: VectorClock.ClocksEntry
	nil,                          // 10: GetInventoryResponse.ItemsEntry
	nil,                          // 11: SyncLedgerRequest.InventoryEntry
	nil,                          // 12: SyncLedgerResponse.MergedInventoryEntry
}
var file_proto_warehouse_proto_depIdxs = []int32{
	9,  // 0: VectorClock.clocks:type_name -> VectorClock.ClocksEntry
	0,  // 1: UpdateStockResponse.current_clock:type_name -> VectorClock
	0,  // 2: GetStockResponse.current_clock:type_name -> VectorClock
	10, // 3: GetInventoryResponse.items:type_name -> GetInventoryResponse.ItemsEntry
	0,  // 4: GetInventoryResponse.current_clock:type_name -> VectorClock
	0,  // 5: SyncLedgerRequest.clock:type_name -> VectorClock
	11, // 6: SyncLedgerRequest.inventory:type_name -> SyncLedgerRequest.InventoryEntry
	0,  // 7: SyncLedgerResponse.merged_clock:type_name -> VectorClock
	12, // 8: SyncLedgerResponse.merged_inventory:type_name -> SyncLedgerResponse.MergedInventoryEntry
	1,  // 9: InventoryManager.UpdateLocalStock:input_type -> UpdateStockRequest
	7,  // 10: InventoryManager.SyncLedger:input_type -> SyncLedgerRequest
	3,  // 11: InventoryManager.GetLocalStock:input_type -> GetStockRequest
	5,  // 12: InventoryManager.GetFullInventory:input_type -> GetInventoryRequest
	2,  // 13: InventoryManager.UpdateLocalStock:output_type -> UpdateStockResponse
	8,  // 14: InventoryManager.SyncLedger:output_type -> SyncLedgerResponse
	4,  // 15: InventoryManager.GetLocalStock:output_type -> GetStockResponse
	6,  // 16: InventoryManager.GetFullInventory:output_type -> GetInventoryResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_warehouse_proto_init() }
func file_proto_warehouse_proto_init() {
	if File_proto_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_warehouse_proto_msgTypes,
	}.Build()
	File_proto_warehouse_proto = out.File
	file_proto_warehouse_proto_goTypes = nil
	file_proto_warehouse_proto_depIdxs = nil
}
