// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/warehouse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryManager_UpdateLocalStock_FullMethodName = "/InventoryManager/UpdateLocalStock"
	InventoryManager_SyncLedger_FullMethodName       = "/InventoryManager/SyncLedger"
	InventoryManager_GetLocalStock_FullMethodName    = "/InventoryManager/GetLocalStock"
	InventoryManager_GetFullInventory_FullMethodName = "/InventoryManager/GetFullInventory"
)

// InventoryManagerClient is the client API for InventoryManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryManagerClient interface {
	UpdateLocalStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
	SyncLedger(ctx context.Context, in *SyncLedgerRequest, opts ...grpc.CallOption) (*SyncLedgerResponse, error)
	GetLocalStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	GetFullInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
}

type inventoryManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryManagerClient(cc grpc.ClientConnInterface) InventoryManagerClient {
	return &inventoryManagerClient{cc}
}

func (c *inventoryManagerClient) UpdateLocalStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStockResponse)
	err := c.cc.Invoke(ctx, InventoryManager_UpdateLocalStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryManagerClient) SyncLedger(ctx context.Context, in *SyncLedgerRequest, opts ...grpc.CallOption) (*SyncLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncLedgerResponse)
	err := c.cc.Invoke(ctx, InventoryManager_SyncLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryManagerClient) GetLocalStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, InventoryManager_GetLocalStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryManagerClient) GetFullInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryManager_GetFullInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryManagerServer is the server API for InventoryManager service.
// All implementations must embed UnimplementedInventoryManagerServer
// for forward compatibility.
type InventoryManagerServer interface {
	UpdateLocalStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error)
	SyncLedger(context.Context, *SyncLedgerRequest) (*SyncLedgerResponse, error)
	GetLocalStock(context.Context, *GetStockRequest) (*GetStockResponse, error)
	GetFullInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	mustEmbedUnimplementedInventoryManagerServer()
}

// UnimplementedInventoryManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryManagerServer struct{}

func (UnimplementedInventoryManagerServer) UpdateLocalStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLocalStock not implemented")
}
func (UnimplementedInventoryManagerServer) SyncLedger(context.Context, *SyncLedgerRequest) (*SyncLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncLedger not implemented")
}
func (UnimplementedInventoryManagerServer) GetLocalStock(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocalStock not implemented")
}
func (UnimplementedInventoryManagerServer) GetFullInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFullInventory not implemented")
}
func (UnimplementedInventoryManagerServer) mustEmbedUnimplementedInventoryManagerServer() {}
func (UnimplementedInventoryManagerServer) testEmbeddedByValue()                          {}

// UnsafeInventoryManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryManagerServer will
// result in compilation errors.
type UnsafeInventoryManagerServer interface {
	mustEmbedUnimplementedInventoryManagerServer()
}

func RegisterInventoryManagerServer(s grpc.ServiceRegistrar, srv InventoryManagerServer) {
	// If the following call panics, it indicates UnimplementedInventoryManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryManager_ServiceDesc, srv)
}

func _InventoryManager_UpdateLocalStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryManagerServer).UpdateLocalStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryManager_UpdateLocalStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryManagerServer).UpdateLocalStock(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryManager_SyncLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryManagerServer).SyncLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryManager_SyncLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryManagerServer).SyncLedger(ctx, req.(*SyncLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryManager_GetLocalStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryManagerServer).GetLocalStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryManager_GetLocalStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryManagerServer).GetLocalStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryManager_GetFullInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryManagerServer).GetFullInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryManager_GetFullInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryManagerServer).GetFullInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryManager_ServiceDesc is the grpc.ServiceDesc for InventoryManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InventoryManager",
	HandlerType: (*InventoryManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLocalStock",
			Handler:    _InventoryManager_UpdateLocalStock_Handler,
		},
		{
			MethodName: "SyncLedger",
			Handler:    _InventoryManager_SyncLedger_Handler,
		},
		{
			MethodName: "GetLocalStock",
			Handler:    _InventoryManager_GetLocalStock_Handler,
		},
		{
			MethodName: "GetFullInventory",
			Handler:    _InventoryManager_GetFullInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/warehouse.proto",
}
